{% set version = "0.5.18" %}
{% set name = "PyVTK" %}
{% set sha256 = "608b509b0da4525ad43078b3a60185c359c16f07a2f6b44fbd6f28fb4b9c4e53" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - numpy >=1.11
    - six
  run:
    - python
    - numpy >=1.11
    - six

test:
  imports:
    - pyvtk
    - pyvtk.common
    - pyvtk.Normals
    - pyvtk.Scalars
    - pyvtk.Data
    - pyvtk.DataSet

about:
  home: https://github.com/pearu/pyvtk
  license: BSD-3-Clause
  license_family: BSD
  # included in post-0.5.18 "master" branch
  # https://github.com/pearu/pyvtk/issues/13
  license_file: LICENSE
  summary: PyVTK tools for manipulating Visualization Toolkit (VTK) files in Python
  doc_url: https://github.com/pearu/pyvtk/tree/master/examples
  dev_url: https://github.com/pearu/pyvtk

  description: |
    PyVTK provides tools for manipulating Visualization Toolkit (VTK)
    files in Python. See
    https://github.com/pearu/pyvtk/blob/master/README.md
    for more details.

extra:
  recipe-maintainers:
    - fangohr
    - marijanbeg
    - takluyver
    - davidcortesortuno
    - rpep
